In [25]:
from task_maker import create_task
import pandas as pd
from itertools import product
import numpy as np

In [26]:
filename = "task_template.json"

In [27]:
num_tasks = 500

dataset = []
for _ in range(num_tasks):
    task = create_task(filename)
    dataset.append(task)
df = pd.DataFrame(dataset)

In [28]:
df.head()

,red_cube_start,blue_cube_start,yellow_cube_start,green_cube_start,Text Question,block_for_task,cat,other_blocks,red_cube_goal,blue_cube_goal,yellow_cube_goal,green_cube_goal
0,"(-0.15, 0.1, 0.02)","(-0.15, 0.3666666666666667, 0.02)","(-0.15, 0.5, 0.02)","(0.14999999999999997, 0.23333333333333334, 0.02)",Take the block that is coloured red and place it -2 horizontally and 3 vertically relative to the block that is coloured blue,0,1,1,"(-2.15, 3.3666666666666667, 0.02)","(-0.15, 0.3666666666666667, 0.02)","(-0.15, 0.5, 0.02)","(0.14999999999999997, 0.23333333333333334, 0.02)"
1,"(0.14999999999999997, 0.23333333333333334, 0.02)","(-0.15, 0.1, 0.02)","(-0.15, 0.23333333333333334, 0.02)","(0.14999999999999997, 0.1, 0.02)",Take the block that is coloured green and place it at [0. 0.1],3,0,None,"(0.14999999999999997, 0.23333333333333334, 0.02)","(-0.15, 0.1, 0.02)","(-0.15, 0.23333333333333334, 0.02)","(0.0, 0.1, 0.02)"
2,"(0.0, 0.23333333333333334, 0.02)","(0.3, 0.5, 0.02)","(-0.3, 0.3666666666666667, 0.02)","(0.0, 0.3666666666666667, 0.02)",Take the block that is coloured green and place it at [0.3 0.1],3,0,None,"(0.0, 0.23333333333333334, 0.02)","(0.3, 0.5, 0.02)","(-0.3, 0.3666666666666667, 0.02)","(0.3, 0.1, 0.02)"
3,"(-0.3, 0.5, 0.02)","(0.14999999999999997, 0.23333333333333334, 0.02)","(0.0, 0.5, 0.02)","(0.3, 0.1, 0.02)",Take the block that is coloured red and place it at [0.3 0.23333333],0,0,None,"(0.3, 0.23333333333333334, 0.02)","(0.14999999999999997, 0.23333333333333334, 0.02)","(0.0, 0.5, 0.02)","(0.3, 0.1, 0.02)"
4,"(0.0, 0.5, 0.02)","(0.14999999999999997, 0.3666666666666667, 0.02)","(-0.15, 0.23333333333333334, 0.02)","(-0.3, 0.5, 0.02)",Take the block that is coloured matches stop signs and place it between the blocks that are coloured green and coloured blue,0,2,"[3, 1]","(0.3, 0.23333333333333334, 0.02)","(0.14999999999999997, 0.3666666666666667, 0.02)","(-0.15, 0.23333333333333334, 0.02)","(-0.3, 0.5, 0.02)"

In [29]:
def is_valid(x):
    
    end_locs = (np.array(x['red_cube_goal']), 
                np.array(x['blue_cube_goal']), 
                np.array(x['green_cube_goal']), 
                np.array(x['yellow_cube_goal']))
    indices = list(range(4))
    dists = []
    for a, b in product(indices, repeat=2):
        if a != b:
            dists.append(np.linalg.norm(end_locs[a] - end_locs[b]))
    return min(dists)

In [30]:
df['goal_dist'] = df.apply(is_valid, axis=1)

In [31]:
pd.set_option('display.max_colwidth', None)

In [32]:
df[df['goal_dist'] == 0]#[['Text Question'] + [i for i in df.columns.tolist() if 'goal' in i]]

Empty DataFrame
Columns: [red_cube_start, blue_cube_start, yellow_cube_start, green_cube_start, Text Question, block_for_task, cat, other_blocks, red_cube_goal, blue_cube_goal, yellow_cube_goal, green_cube_goal, goal_dist]
Index: []

In [ ]:
df.to_csv("task_dataset.csv", index=False)